version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URI=mysql://root:Hibaabdelli19%40@host.docker.internal/herbal_medicine
      - FLASK_ENV=production
      - SECRET_KEY=your_default_secret_key
      - JWT_SECRET_KEY=your_default_jwt_secret_key
      - GOOGLE_CLIENT_ID=152838997088-k5j34u36gv8osrjej8pnkrngg9c85gst.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_NEWS_API_KEY=3cd86a5483c44de4acfa3ddedfc8a6c7
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Hibaabdelli19@
      MYSQL_DATABASE: herbal_medicine
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
