"""Initial migration

Revision ID: 399ef5ecfcd5
Revises: 
Create Date: 2024-12-28 09:45:59.255765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '399ef5ecfcd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('review',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('review',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
