"""Your migration message

Revision ID: f0d4e5fbcbb9
Revises: 7ca3d7a4b8af
Create Date: 2024-12-29 20:44:53.299000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0d4e5fbcbb9'
down_revision = '7ca3d7a4b8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_index('url')

    op.drop_table('news_article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('published_at', mysql.DATETIME(), nullable=False),
    sa.Column('source_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('keywords', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.create_index('url', ['url'], unique=True)

    # ### end Alembic commands ###
